apiVersion: v1
kind: Service
metadata:
  name: micro-front-main
spec:
  type: LoadBalancer
  selector:
    app: mfm
  ports:
  - protocol: TCP
    port: 30812
    targetPort: 443

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-mfm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mfm
  template:
    metadata:
      labels:
        app: mfm
    spec:
      imagePullSecrets:
        - name: ghcr-login-secret
      containers:
      - name: gestor-jobs-container
        image: ghcr.io/forte-gestorjobs/micro-frontend-main:latest
        ports:
        - containerPort: 8080