apiVersion: v1
kind: Service
metadata:
  name: micro-cloud-tareas
spec:
  type: LoadBalancer
  selector:
    app: mct
  ports:
  - protocol: TCP
    port: 30809
    targetPort: 443
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-mct
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mct
  template:
    metadata:
      labels:
        app: mct
    spec:
      imagePullSecrets:
        - name: ghcr-login-secret
      containers:
      - name: gestor-jobs-container
        image: ghcr.io/forte-gestorjobs/micro-cloud-tareas
        ports:
        - containerPort: 8082
        env:
            - name: MCT_DBUSER
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: MCT_DBUSER
            - name: MCT_DBPWD
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: MCT_DBPWD
            - name: MCT_DBNAME
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: MCT_DBNAME
            - name: MCT_DBHOST
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: MCT_DBHOST
            - name: MCT_DBPORT
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: MCT_DBPORT
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: AWS_SECRET_KEY
            - name: AWS_REGION
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: AWS_REGION
